
export const LOAD_RECIPES = 'LOAD_RECIPES'
export const ADD_RECIPE = 'ADD_RECIPE'
export const LIKE_RECIPE = 'LIKE_RECIPE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const CURRENT_USER = 'CURRENT_USER'
export const ADD_USER  = 'ADD_USER'
export const LOAD_USERS = 'LOAD_USERS'

export const CREATE_USER_SESSION  = 'CREATE_USER_SESSION'

export const LOAD_SESSIONS = 'LOAD_SESSIONS'

export const CREATE_COOKING_SESSION = 'CREATE_COOKING_SESSION'
export const CREATE_USER_COOKING_SESSION = 'CREATE_USER_COOKING_SESSION'
export const LOAD_COOKING_SESSIONS = 'LOAD_COOKING_SESSIONS'
export const JOIN_A_CLASS = 'JOIN_A_CLASS'

export const LOAD_COMMENTS = 'LOAD_COMMENTS'

export const LOGOUT = 'LOGOUT'

export const DELETE_COOKING_SESSION = 'DELETE_COOKING_SESSION'



