
export const LOAD_RECIPES = 'LOAD_RECIPES'
export const ADD_RECIPE = 'ADD_RECIPE'
export const LIKE_RECIPE = 'LIKE_RECIPE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const CURRENT_USER = 'CURRENT_USER'
export const ADD_USER  = 'ADD_USER'
export const LOAD_USERS = 'LOAD_USERS'
// export const UPDATE_USER = 'UPDATE_USER'

export const CREATE_COOKING_SESSION = 'CREATE_COOKING_SESSION'
// export const DELETE_COOKING_SESSION = 'DELETE_COOKING_SESSION'
// export const UPDATE_COOKING_SESSION = 'UPDATE_COOKING_SESSION'
